local sprite=Sprite(110,97,ColorMode.RGB)
local layer=sprite.layers[1];layer.name='BLOCKOUT — six-pose walk'
sprite:newCel(layer,1,Image{fromFile='C:/Users/simcr/projects/stick-rts-visual-proof/assets/art/runtime-candidates/sunmeadow/warrior/sunmeadow-warrior-walk-v15-six-pose-mannequin-blockout/frame-01-contact-a.png'})
sprite:newFrame()
sprite:newCel(layer,2,Image{fromFile='C:/Users/simcr/projects/stick-rts-visual-proof/assets/art/runtime-candidates/sunmeadow/warrior/sunmeadow-warrior-walk-v15-six-pose-mannequin-blockout/frame-02-down-a.png'})
sprite:newFrame()
sprite:newCel(layer,3,Image{fromFile='C:/Users/simcr/projects/stick-rts-visual-proof/assets/art/runtime-candidates/sunmeadow/warrior/sunmeadow-warrior-walk-v15-six-pose-mannequin-blockout/frame-03-passing-a.png'})
sprite:newFrame()
sprite:newCel(layer,4,Image{fromFile='C:/Users/simcr/projects/stick-rts-visual-proof/assets/art/runtime-candidates/sunmeadow/warrior/sunmeadow-warrior-walk-v15-six-pose-mannequin-blockout/frame-04-contact-b.png'})
sprite:newFrame()
sprite:newCel(layer,5,Image{fromFile='C:/Users/simcr/projects/stick-rts-visual-proof/assets/art/runtime-candidates/sunmeadow/warrior/sunmeadow-warrior-walk-v15-six-pose-mannequin-blockout/frame-05-down-b.png'})
sprite:newFrame()
sprite:newCel(layer,6,Image{fromFile='C:/Users/simcr/projects/stick-rts-visual-proof/assets/art/runtime-candidates/sunmeadow/warrior/sunmeadow-warrior-walk-v15-six-pose-mannequin-blockout/frame-06-passing-b.png'})
app.command.SaveFile{filename='C:/Users/simcr/projects/stick-rts-visual-proof/assets/art/editable/sunmeadow/warrior/sunmeadow-warrior-walk-v15-six-pose-mannequin-blockout.aseprite'};app.exit()